### ISSUE TITLE
다른 User 에 대한 프로필, 포스팅을 보여주는 페이지 

### ISSUE THREAD

**Issue by P-iknow** [P-iknow/sns#28]
## TODO
- [x] porstCrard 에서 Avatar 부분 링크로 변환해서 해당 유저의 정보와 post를 가져오는 페이지로 이동시키키 
- [x] redux, redux-saga 다른 유저 가져오는 로직 반영하기 
- [x] `user/:id` 에 대한 라우터 만들기
