### ISSUE TITLE
프로필 페이지 데이터 로딩 

### ISSUE THREAD

**Issue by P-iknow** [P-iknow/sns#44]
# TODO

### 컴포넌트 

- [ ] 내가 쓴 게시글도 함께 보여주기 
- [ ] `<List dataSource ={}> ` 데이터 소스 실 데이터로 넣어주기
- [ ] onUnFollow 함수
- [ ] onRemoveFollower 함수 

### Saga User

- [ ] Load Followers
- [ ] Load Followings
- [ ] Remove Follower

## Back

- [ ] GET api/:id/followings 
- [ ] GET api/:id/followers
- [ ] DELETE api/:id/follower
